//! C backend — walks the AST and emits portable C11 source.
//!
//! Phase 1 scope is deliberately narrow: enough to compile
//! `examples/hello_world.hm` and trivial arithmetic programs. Shapes,
//! sum types, ownership, generics, and AI constructs are Phase 2+.
//!
//! ## Type mapping (surface HMAT → C)
//!
//! | HMAT   | C              |
//! |--------|----------------|
//! | `int`  | `int64_t`      |
//! | `float`| `double`       |
//! | `bool` | `bool`         |
//! | `str`  | `const char *` |
//! | `()`   | `void`         |
//!
//! ## Builtins
//!
//! `print(x: str)` lowers to `printf("%s\n", x)`. Later phases will
//! replace this with a real `io` module once the prelude loader lands.

use std::fmt::Write as _;

use crate::ast::{
    BinOp, Binary, Block, Call, Expression, FunctionDecl, Item, LetStmt, Literal, Program,
    ReturnStmt, Statement, TypeRef, UnOp, Unary,
};

/// Emits C source text for a HMAT [`Program`].
pub fn emit(program: &Program) -> String {
    let mut e = Emitter::new();
    e.emit_program(program);
    e.out
}

struct Emitter {
    out: String,
    indent: usize,
}

impl Emitter {
    fn new() -> Self {
        let mut out = String::new();
        out.push_str("// Generated by hmatc — do not edit.\n");
        out.push_str("#include <stdio.h>\n");
        out.push_str("#include <stdint.h>\n");
        out.push_str("#include <stdbool.h>\n");
        out.push_str("#include <math.h>\n\n");
        Self { out, indent: 0 }
    }

    fn emit_program(&mut self, p: &Program) {
        for item in &p.items {
            match item {
                Item::Function(f) => self.emit_function(f),
            }
        }
    }

    fn emit_function(&mut self, f: &FunctionDecl) {
        let is_main = f.name.name == "main";
        // `fn main()` with no explicit return type is implicitly `int` so
        // the OS gets a meaningful exit code. Everything else defaults to
        // `void` until Phase 2 wires inferred return types.
        let ret = match &f.return_type {
            Some(tr) => map_type(tr).to_string(),
            None if is_main => "int".to_string(),
            None => "void".to_string(),
        };

        let _ = write!(self.out, "{} {}(", ret, f.name.name);
        if f.params.is_empty() {
            self.out.push_str("void");
        } else {
            for (i, p) in f.params.iter().enumerate() {
                if i > 0 {
                    self.out.push_str(", ");
                }
                let _ = write!(self.out, "{} {}", map_type(&p.ty), p.name.name);
            }
        }
        self.out.push_str(") {\n");

        self.indent = 1;
        self.emit_block(&f.body);
        // Auto-return 0 from `main` when the source did not write one —
        // otherwise clang warns and some shells see garbage exit codes.
        if is_main && f.return_type.is_none() && !ends_with_return(&f.body) {
            self.push_line("return 0;");
        }
        self.indent = 0;

        self.out.push_str("}\n\n");
    }

    fn emit_block(&mut self, b: &Block) {
        for s in &b.statements {
            self.emit_stmt(s);
        }
    }

    fn emit_stmt(&mut self, s: &Statement) {
        match s {
            Statement::Let(l) => self.emit_let(l),
            Statement::Return(r) => self.emit_return(r),
            Statement::Expr(e) => {
                let expr = self.emit_expr(e);
                let line = format!("{};", expr);
                self.push_line(&line);
            }
        }
    }

    fn emit_let(&mut self, l: &LetStmt) {
        let value = self.emit_expr(&l.value);
        // When the user declares a type, honour it. When they don't, defer
        // to clang's `__auto_type` extension rather than re-running type
        // inference at codegen time. Both gcc and clang accept it.
        let ty = match &l.ty {
            Some(tr) => map_type(tr).to_string(),
            None => "__auto_type".to_string(),
        };
        let qualifier = if l.mutable { "" } else { "const " };
        let line = format!("{}{} {} = {};", qualifier, ty, l.name.name, value);
        self.push_line(&line);
    }

    fn emit_return(&mut self, r: &ReturnStmt) {
        match &r.value {
            Some(v) => {
                let expr = self.emit_expr(v);
                let line = format!("return {};", expr);
                self.push_line(&line);
            }
            None => self.push_line("return;"),
        }
    }

    fn emit_expr(&mut self, e: &Expression) -> String {
        match e {
            Expression::Literal(l) => emit_literal(l),
            Expression::Identifier(id) => id.name.clone(),
            Expression::Call(c) => self.emit_call(c),
            Expression::FieldAccess(fa) => {
                let base = self.emit_expr(&fa.base);
                format!("{}.{}", base, fa.field.name)
            }
            Expression::Binary(b) => self.emit_binary(b),
            Expression::Unary(u) => self.emit_unary(u),
            Expression::Grouped(g) => {
                let inner = self.emit_expr(&g.inner);
                format!("({})", inner)
            }
        }
    }

    fn emit_binary(&mut self, b: &Binary) -> String {
        let lhs = self.emit_expr(&b.lhs);
        let rhs = self.emit_expr(&b.rhs);
        match b.op {
            // HMAT `^` is exponentiation, not XOR — lower to libm `pow`.
            BinOp::Pow => format!("pow({}, {})", lhs, rhs),
            BinOp::And => format!("({} && {})", lhs, rhs),
            BinOp::Or => format!("({} || {})", lhs, rhs),
            _ => format!("({} {} {})", lhs, c_binop(b.op), rhs),
        }
    }

    fn emit_unary(&mut self, u: &Unary) -> String {
        let operand = self.emit_expr(&u.operand);
        match u.op {
            UnOp::Neg => format!("(-{})", operand),
            UnOp::Not => format!("(!{})", operand),
        }
    }

    fn emit_call(&mut self, c: &Call) -> String {
        // `print` is the one builtin Phase 1 knows about; everything else
        // is treated as a direct user-defined call. The prelude will take
        // over once Phase 2 wires import resolution.
        if let Expression::Identifier(id) = &*c.callee {
            if id.name == "print" {
                if let [arg] = c.args.as_slice() {
                    let a = self.emit_expr(arg);
                    return format!("printf(\"%s\\n\", {})", a);
                }
            }
        }

        let callee = self.emit_expr(&c.callee);
        let args: Vec<String> = c.args.iter().map(|a| self.emit_expr(a)).collect();
        format!("{}({})", callee, args.join(", "))
    }

    fn push_line(&mut self, s: &str) {
        for _ in 0..self.indent {
            self.out.push_str("    ");
        }
        self.out.push_str(s);
        self.out.push('\n');
    }
}

fn ends_with_return(b: &Block) -> bool {
    matches!(b.statements.last(), Some(Statement::Return(_)))
}

fn emit_literal(l: &Literal) -> String {
    match l {
        // Suffix `LL` ensures the literal is wide enough for int64_t on
        // platforms where plain `int` is 32-bit.
        Literal::Int { value, .. } => format!("((int64_t){}LL)", value),
        Literal::Float { value, .. } => format_float(*value),
        Literal::Str { value, .. } => format!("\"{}\"", escape_c_string(value)),
        // Phase 1 treats f-strings as plain string literals — the parser
        // keeps the body unsplit until Phase 2 wires real interpolation.
        Literal::FStr { value, .. } => format!("\"{}\"", escape_c_string(value)),
        Literal::Bool { value, .. } => {
            if *value {
                "true".to_string()
            } else {
                "false".to_string()
            }
        }
        Literal::Nil { .. } => "NULL".to_string(),
    }
}

fn format_float(v: f64) -> String {
    // `{:?}` guarantees a decimal point, which matters — `1` and `1.0` are
    // lexed differently by C, and we want the value to keep its float-ness.
    let s = format!("{:?}", v);
    if s.contains('.') || s.contains('e') || s.contains("inf") || s.contains("NaN") {
        s
    } else {
        format!("{}.0", s)
    }
}

fn escape_c_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) >= 0x20 && (c as u32) < 0x7f => out.push(c),
            c => {
                // Encode non-ASCII (and control bytes) as three-digit octal
                // escapes. Hex escapes (`\xNN`) read unlimited hex digits in
                // C, so `"\xe2hi"` silently folds into a single wide code
                // point. `\NNN` is capped at three octal digits by the
                // standard, so every escape self-terminates.
                let mut buf = [0u8; 4];
                for &b in c.encode_utf8(&mut buf).as_bytes() {
                    let _ = write!(out, "\\{:03o}", b);
                }
            }
        }
    }
    out
}

fn c_binop(op: BinOp) -> &'static str {
    match op {
        BinOp::Add => "+",
        BinOp::Sub => "-",
        BinOp::Mul => "*",
        BinOp::Div => "/",
        BinOp::Mod => "%",
        BinOp::Eq => "==",
        BinOp::NotEq => "!=",
        BinOp::Lt => "<",
        BinOp::LtEq => "<=",
        BinOp::Gt => ">",
        BinOp::GtEq => ">=",
        // Handled in `emit_binary` as special cases.
        BinOp::Pow | BinOp::And | BinOp::Or => unreachable!("handled in emit_binary"),
    }
}

fn map_type(tr: &TypeRef) -> &'static str {
    match tr.name.as_str() {
        "int" | "i64" => "int64_t",
        "i8" => "int8_t",
        "i16" => "int16_t",
        "i32" => "int32_t",
        "i128" => "__int128",
        "uint" | "u64" => "uint64_t",
        "u8" => "uint8_t",
        "u16" => "uint16_t",
        "u32" => "uint32_t",
        "u128" => "unsigned __int128",
        "float" | "f64" => "double",
        "f32" => "float",
        "bool" => "bool",
        "str" => "const char *",
        // Phase 1 fallback — user types arrive in Phase 2 when `shape`
        // lowering lands.
        _ => "void *",
    }
}
